# Generated by Django 4.2.29 on 2026-04-07 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_add_database_indices'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='posts_post_author__f8ea20_idx',
            old_name='posts_post_author_created_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='posts_post_created_d09949_idx',
            old_name='posts_post_created_deleted_idx',
        ),
    ]
