# Generated by Django 4.2.29 on 2026-04-07 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0006_add_database_indices'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='interaction_post_id_a6e852_idx',
            old_name='interactions_comment_post_created_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='interaction_created_00c2fb_idx',
            old_name='interactions_report_created_status_idx',
        ),
        migrations.RenameIndex(
            model_name='vote',
            new_name='interaction_post_id_4d3b3f_idx',
            old_name='interactions_vote_post_idx',
        ),
    ]
